apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fohm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-fohm
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-fohm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fohm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-fohm
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-hiwr-tenant/dotnet-component/devfile-sample-dotnet60-basic-fohm@sha256:b2a27715680fbd86602f5328fb685f8a180bfc969b420aa0984a90e420ceeeb5
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
